version: "3.9"
services:
  platform:
    image: ghcr.io/alvanrahimli/postapic:master
    container_name: postapic
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9010:8080"
    volumes:
      - "./images/:/app/images/"
      - "./db/:/app/db/"

